# -*- coding: utf-8 -*-
"""Proyecto_Progra_Cienc_Datos.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1oy2h5aYLYVradbUrKEXSmBUsk8d649PD
"""

#Importe de librerias necesarias
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.pipeline import Pipeline
from sklearn.base import BaseEstimator, TransformerMixin
from sklearn.impute import SimpleImputer
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import FunctionTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder, MinMaxScaler, OrdinalEncoder
#Lectura de datos sucios del data set
data = pd.read_csv('dataset_clientes.csv')
data.head()

"""## Analisis de tipos de datos de cada categoria (columna)"""

data.info()

"""## Descripcion analisis valores columnas cuantitativas
Identificamos que las columnas "tiene_tarjeta_credito" y "abandono" debe ser booleano y no entero, ya que sus valores o son 1 o son 0.
"""

data.drop(columns=["id_cliente"]).describe()

"""## Descripcion y analisis columnas cualitativas
columnas ordinales: "uso_app","tipo_plan"

columnas nominales: "genero","region","estado_civil","canal_registro","dia_semana_registro"
"""

data.describe(include="object")

data.region.unique()

data.estado_civil.unique()

data.tipo_plan.unique()

data.uso_app.unique()

data.canal_registro.unique()

data.genero.unique()

"""##Analisis de nulos
Determinamos que "ingreso_mensual" ,"gastomensual"y"score_crediticio" contienen la misma cantidad de nulos.
"""

data.isnull().sum()
#Obtencion de datos nulos

"""##Analisis de duplicados

"""

data.duplicated().sum()
#Obtencion de duplicados
data[data.duplicated(keep=False)].sort_values(by='id_cliente')

"""##Analisis de atipicos
Definimos que "tiene_tarjeta_credito"y"abandono" no son candidatos para la busqueda de atipicos, ya que cuentan como categoricos (booleanos).
Además podemos identificar las columnas "ingreso_mensual",	"gasto_mensual",	"deuda_total",	"score_crediticio" con alta probabilidad de tener datos atipicos.

"""

registro_atipicos=["edad",	"ingreso_mensual",	"gasto_mensual",	"deuda_total",	"score_crediticio",	"antiguedad_meses",	"frecuencia_compra",	"ultima_compra_dias",	"num_productos",	"hora_registro"]
fig, axes = plt.subplots(1, 10, figsize=(20,20))
axes = axes.flatten()  # convierte la matriz de ejes en un vector
for i, col in enumerate(registro_atipicos):
  data[col].plot(kind='box',figsize=(12,12), ax=axes[i])
  axes[i].tick_params(axis="x", labelrotation=45)

plt.suptitle("Análisis de atípicos", fontsize=16, fontweight="bold")
plt.tight_layout()

plt.show()

"""##Clase para winsorizar los datos
Esto con el fin de limpiar los outliers.
"""

class Winsorizer(BaseEstimator, TransformerMixin):

  def __init__(self, limits=(0.05, 0.05)):
    self.limits = limits

  def fit(self, X, y=None):
    # Guardar nombres si es DataFrame, si no generar nombres genéricos
    if isinstance(X, pd.DataFrame):
      self.columns_ = X.columns
    else:
      self.columns_ = np.arange(X.shape[1])
    return self

  def transform(self, X):
    X = pd.DataFrame(X, columns=self.columns_)
    for col in self.columns_:
      lower = X[col].quantile(self.limits[0])
      upper = X[col].quantile(1 - self.limits[1])
      X = X.astype("float64")
      X[col] = np.clip(X[col], lower, upper)
    return X

  def get_feature_names_out(self, input_features=None):
    if input_features is None:
      return np.array(self.columns_)
    else:
      return np.array(input_features)

"""##Tratamiento de duplicados"""

def eliminar_duplicados(X):
  return X.drop_duplicates()